### ISSUE TITLE
can't pod xcode7

### ISSUE THREAD

**Issue by longxianlin** [aschuch/QRCode#14]
ios9

**Comment by aschuch** [comment]
Can you please elaborate on the exact issue you are seeing?

**Comment by longxianlin** [comment]
let cardNumber = 918822
        let qrcode1 = QRCode("(cardNumber)")
        qrcode1.size = cardImageView.bounds.size
        qrcode1.color = CIColor(rgba: "16a085")
        qrCode.backgroundColor = CIColor(rgba: "000")
        cardImageView.image = qrcode1!.image

error: cannot assign to property: is immutable

**Comment by aschuch** [comment]
You have to declare your variable as `var`.
