### ISSUE TITLE
Created images not working with UIViewContentModeScaleAspectFit

### ISSUE THREAD

**Issue by Querschlag** [aschuch/QRCode#17]
The created image gets streched even when using UIViewContentModeScaleAspectFit on a UIImageView.

Fixed it by adding another conversion step (CIImage -> CGImage -> UIImage).
https://github.com/Querschlag/QRCode/commit/f603d590bda07ac81f9e3cdd09ebef6d53853e41

Update: This also fixes image preview in the debugger.

**Comment by aschuch** [comment]
Cool, please open a pull request if you want to have this merged.

**Comment by aschuch** [comment]
Merged
