### ISSUE TITLE
Converting image to NSData return nil

### ISSUE THREAD

**Issue by ivanovvitaly** [aschuch/QRCode#20]
Hey Guys,

Trying to convert image to nsdata, but receive nil. Tried both PNG and JPEG. 

``` swift
let qrc = QRCode("sample")
let img = UIImagePNGRepresentation(qrc.image!) // img is nil 
```

Please advice

**Comment by kevinrodriguez-io** [comment]
Same problem here, tried with JPG representation and it also returns nil.

**Comment by kevinrodriguez-io** [comment]
Fixed by doing this

```
    let image = YourUIImage

    UIGraphicsBeginImageContext(image.size)

    image.drawInRect(CGRectMake(0, 0, image.size.width, image.size.height))

    let convertibleImage = UIGraphicsGetImageFromCurrentImageContext()

    UIGraphicsEndImageContext()

    return convertibleImage
```

**Comment by aschuch** [comment]
Can you have a look if 5d026ab136ec09868981a14c3ee8618e33b2692d fixes this problem as well?

**Comment by aschuch** [comment]
Can anyone confirm the latest changes in master to fix this issue?

**Comment by kevinrodriguez-io** [comment]
Sorry, i have been very busy, i will test it in this afternoon!!!

Sent from my iPhone

On Mar 12, 2016, at 5:17 AM, Alexander Schuch <notifications@github.com<mailto:notifications@github.com>> wrote:

Can anyone confirm the latest changes in master to fix this issue?

##

**Comment by aschuch** [comment]
Any results?

**Comment by BasThomas** [comment]
This seems to work now. :)

**Comment by aschuch** [comment]
Thanks for the confirmation. 🎉

**Comment by antonioreyna** [comment]
Hello I have the same problem, and i think i have the latest, i installed via cocoapods
