### ISSUE TITLE
how about add NSUrl,String extension

### ISSUE THREAD

**Issue by lacklock** [aschuch/QRCode#24]
i think using extension to invoke have a better experience. like:
`stringA.QRImage()`
this method could have some default parameters,like size or something else.

if you agree with this , I can spend some time work on it,create a pull request

**Comment by kevinrodriguez-io** [comment]
why not doing it yourself?

Like:
`
extension String {
    var qrCode: UIImage? {
        get {
            let qrCode = QRCode(self);
            return qrCode?.image;
        }
    }
}
`
