### ISSUE TITLE
QRCode string encoding

### ISSUE THREAD

**Issue by Querschlag** [aschuch/QRCode#26]
Is there a specific reason why the initialisers for string and NSURL both encode the input as latin1 instead of UTF-8?

```
public init?(_ string: String) {
        if let data = string.dataUsingEncoding(NSISOLatin1StringEncoding) {
            self.data = data
        } else {
            return nil
        }
    }

public init?(_ url: NSURL) {
    if let data = url.absoluteString.dataUsingEncoding(NSISOLatin1StringEncoding) {
        self.data = data
    } else {
        return nil
    }
}
```

**Comment by aschuch** [comment]
The encoding is required by the `CIFilter` that creates the QRCode image.

**Comment by Querschlag** [comment]
Thanks for your explanation.
I experienced that `CIQRCodeGenerator` also supports ECI. So it is possible to use `NSUTF8StringEncoding` which results in a valid QR Code image that scanners can read.

Details: http://stackoverflow.com/questions/31115932/ciqrcodegenerator-with-nsutf8stringencoding
