### ISSUE TITLE
Version 1.0 not available on cocoapods

### ISSUE THREAD

**Issue by djxmax** [aschuch/QRCode#35]
The latest version available on cocoapods is 0.5. Maybe you forgot to update the new version on cocoapods ?

**Comment by mauroandremazzola** [comment]
update your podefile to:
pod 'QRCode', :git => 'https://github.com/aschuch/QRCode'

**Comment by leogiertz** [comment]
Ping @aschuch :)

**Comment by funky-monkey** [comment]
Also for this to work you need to bump the ios version to 9.0 in your podspec. Like so: `s.platform = :ios, "9.0"`

**Comment by le4ker** [comment]
Bump.

@mauroandremazzola this is not the right thing to do (tm), since there can be changes pushed to master that are not backwards compatible.

@aschuch when are you planning to release 1.0 on coccoapods?

Thanks,
:panos

**Comment by aschuch** [comment]
Version 1.0 and 2.0 (Swift 3) has just been pushed to Cocoapods trunk.
