### ISSUE TITLE
Qr code generated in ios7 fuzzy

### ISSUE THREAD

**Issue by wenhongquan** [aschuch/QRCode#4]

**Comment by aschuch** [comment]
Can you please share some code and/or a screenshot and the expected behaviour?

**Comment by wenhongquan** [comment]
## ios7

![img_0246 1](https://cloud.githubusercontent.com/assets/5125739/7582291/a7d4b88c-f8be-11e4-8d67-8928cea5ebac.jpg)

## ios8

![img_0245](https://cloud.githubusercontent.com/assets/5125739/7582292/a8780ae6-f8be-11e4-9add-9812b83f7af7.jpg)

**Comment by wenhongquan** [comment]
```
 qrImage.image = {
            var qrCode = QRCode("sdfgbdfghsrdefthgswdfhsadefhsdefhsawdefhrsdfhsdewfthawedhswdgfhsedghswdehgsderthsderth")!
            qrCode.size = self.qrImage.bounds.size
            qrCode.color = CIColor(rgba: "000000")
            qrCode.backgroundColor = CIColor(rgba: "ffffff")
            return qrCode.image
            }()
```

**Comment by aschuch** [comment]
Can you try to set the error correction, that was added with the latest release, to `.High`?

**Comment by v1n2e7t** [comment]
Was this issue ever fixed?
