### ISSUE TITLE
Pod is still at version 0.5

### ISSUE THREAD

**Issue by BasThomas** [aschuch/QRCode#40]
Can you update the pod on CocoaPods to 1.0 please? :)

**Comment by Said-Re** [comment]
The issue is already created [here](https://github.com/aschuch/QRCode/issues/35).
Use pod `'QRCode', :git => 'https://github.com/aschuch/QRCode'` to have the latest.

**Comment by BasThomas** [comment]
Overlooked. Already using a url to 1.0. :)
