### ISSUE TITLE
Maximum capacity

### ISSUE THREAD

**Issue by le4ker** [aschuch/QRCode#42]
Hi,

What is the maximum capacity that can be encoded for an ASCII encoded string?

Thanks,
:panos

**Comment by aschuch** [comment]
I think its rather a matter of the max length that can be encoded into the QRCode format. 

> Numeric only    Max. 7,089 characters (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
>  Alphanumeric    Max. 4,296 characters (0–9, A–Z [upper-case only], space, $, %, *, +, -, ., /, :)
>  Binary/byte     Max. 2,953 characters (8-bit bytes) (23624 bits)
>  Kanji/Kana  Max. 1,817 characters
> 
> -- Source: http://stackoverflow.com/a/12764370

**Comment by le4ker** [comment]
Thanks Alexander.

And what is the expected behavior when trying to write more data than a qr code can handle?

Shouldn't there be a test that covers that case? :shipit:

**Comment by aschuch** [comment]
To be honest, I don't know. 
A test would be a good idea, do you want to submit a pull request?

**Comment by le4ker** [comment]
We haven't decided if we will choose your library for our product yet, so I can't commit on paying your test debt, yet :smile:

**Comment by blochberger** [comment]
Only bytes and Latin1 encoded strings are supported by the `CIQRCodeGenerator` filter. Therefore no special encoding is used for numeric, alphanumeric, or Kanji/Kana input. Kanji/Kana will not translate to Latin1 and can therefore not be passed as a `String`.

Any interest in a pull request for returning `nil` by the initializer of `QRCode` if the input is exceeding the limit?
