### ISSUE TITLE
Fail when building with Carthage

### ISSUE THREAD

**Issue by Sk92** [aschuch/QRCode#6]
I received this error when i try to install this library with cathage.

In cartfile:
github "aschuch/QRCode"

Error:
**\* Building scheme "QRCode" in Example.xcodeproj
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /project-path/Carthage/Checkouts/QRCode/QRCode/CIColorExtension.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by aschuch** [comment]
What version of Xcode/command line tools are you using?

**Comment by aschuch** [comment]
Are you still experiencing problems with Carthage?

**Comment by aschuch** [comment]
Closing this now, feel free to open again if you are still experiencing issues.

**Comment by elliotstokes** [comment]
I just tried to install with Carthage and got the following error. Looks like swift 2 issues? Im pretty new to swift and carthage so it could very well be me.

**\* Cloning QRCode
**\* Checking out QRCode at "swift-1.1"
**\* xcodebuild output can be found in /var/folders/tf/lbnrkr851qdgcd3dsjz53p1w0000gn/T/carthage-xcodebuild.3dadoB.log
**\* Building scheme "QRCode" in Example.xcodeproj
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift
    CompileSwift normal x86_64 /Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/CIColorExtension.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:49:41: error: cannot use optional chaining on non-optional value of type 'String'
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:60:41: error: cannot force unwrap value of non-optional type 'UIImage'
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:67:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:68:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:72:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:73:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:73:30: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:74:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:75:9: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:81:32: error: value of optional type 'CIFilter?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift:81:44: error: value of optional type 'CIImage?' not unwrapped; did you mean to use '!' or '?'?
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/CIColorExtension.swift:32:26: error: use of unresolved identifier 'countElements'
/Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/CIColorExtension.swift:58:13: error: 'println' has been renamed to 'print'
A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/QRCode.swift
    CompileSwift normal x86_64 /Users/a/Sites/stuff/swift/test/Carthage/Checkouts/QRCode/QRCode/CIColorExtension.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by aschuch** [comment]
This is due to the fact that Cartahge picked the `swift-1.1` tag per default. I've since removed the tag.
Please try again to see if it works for you now.
